name: Dev CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
      
  pull_request:

env:
  AWS_REGION: eu-west-2
  STACK_NAME: service-ai-analysis
  STAGE: dev

jobs:
  deploy-dev:
    name: Deploy to AWS (Dev)
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy Stack
        run: |
          cdk deploy --require-approval never || {
            echo '❌ Deployment failed. Checking rollback options...';
            if [ "$AUTO_ROLLBACK" == "yes" ]; then
              echo '🔄 Rolling back...';
              aws cloudformation rollback-stack --stack-name ${STACK_NAME}
            else
              echo '🛑 Manual rollback required!';
            fi
          }